---
- name: Install MariaBD
  yum: name={{ item }} state=latest
  with_items:
    - mariadb-server
    - mariadb
    - MySQL-python
    
- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes
  
- name: Set root Password
  mysql_user: login_password={{ mysql_root_password }} check_implicit_admin=yes name=root host={{ item }} password={{ mysql_root_password }} state=present 
  with_items:
    - localhost
    - 127.0.0.1
    - ::1  
  

- name: Template MariaDB config
  template: src=templates/my.cnf.j2 dest=/etc/my.cnf
 # notify: reload mariadb 

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present

- name: Create mysql user
  mysql_user: 
    name={{ wp_mysql_user }} 
    password={{ wp_mysql_password }} 
    priv=*.*:SELECT

