---
- name: Install MariaBD
  yum: name={{ item }} state=latest
  with_items:
    - mariadb-server
    - mariadb
    - MySQL-python
    
- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes


- name: Template MariaDB config
  template: src=templates/my.cnf.j2 dest=/etc/my.cnf
 # notify: reload mariadb 

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present

- name: Create mysql user
  mysql_user: 
    name={{ wp_mysql_user }} 
    password={{ wp_mysql_password }} 
    priv=*.*:ALL

